var Database = require('better-sqlite3');
var path = require('path');
var db = new Database(path.join(__dirname, '../../trader.db'));
function getCandles(sym,tf){return db.prepare('SELECT open_time,open,high,low,close,volume FROM candles WHERE symbol=? AND timeframe=? ORDER BY open_time ASC').all(sym,tf);}
function calcBB(closes,p,m){var b=[];for(var i=0;i<closes.length;i++){if(i<p-1){b.push(null);continue;}var sl=closes.slice(i-p+1,i+1);var mn=sl.reduce(function(a,b){return a+b;},0)/p;var vr=sl.reduce(function(a,b){return a+(b-mn)*(b-mn);},0)/p;var s=Math.sqrt(vr);b.push({upper:mn+m*s,lower:mn-m*s});}return b;}
function calcMFI(H,L,C,V,p){var m=new Array(C.length).fill(null);var tp=C.map(function(c,i){return(H[i]+L[i]+c)/3;});var mf=tp.map(function(t,i){return t*V[i];});for(var i=p;i<C.length;i++){var pf=0,nf=0;for(var j=i-p+1;j<=i;j++){if(tp[j]>tp[j-1])pf+=mf[j];else nf+=mf[j];}m[i]=nf===0?100:100-100/(1+pf/nf);}return m;}
function wf(sigs){var n=3,fs=Math.floor(sigs.length/n),res=[];for(var f=0;f<n;f++){var st=f*fs,en=f===n-1?sigs.length:st+fs;var fold=sigs.slice(st,en);res.push({wr:fold.length>0?fold.filter(function(s){return s.win;}).length/fold.length:0,n:fold.length});}var wrs=res.map(function(r){return r.wr;});var avg=wrs.reduce(function(a,b){return a+b;},0)/n;var vr=wrs.reduce(function(a,b){return a+(b-avg)*(b-avg);},0)/n;return{avgWR:avg*100,sigma:Math.sqrt(vr)*100,folds:res,total:sigs.length};}
function sk(op,cl,i){var d=cl[i]>op[i]?1:-1;var s=0;for(var j=i;j>=0;j--){if((cl[j]>op[j]?1:-1)===d)s++;else break;}return{streak:s,dir:d};}
function rep(lbl,sigs){if(sigs.length<20){console.log(lbl+': T='+sigs.length+' (too few)');return;}var r=wf(sigs);var fs=r.folds.map(function(f){return(f.wr*100).toFixed(1)+'%['+f.n+']';}).join('/');var p=r.avgWR>=65&&r.sigma<=8&&r.total>=50;console.log(lbl+': WR='+r.avgWR.toFixed(1)+'% sigma='+r.sigma.toFixed(1)+'% T='+r.total+' ['+fs+'] '+(p?'*** PASS ***':''));}
var GH=new Set([10,11,12,21]);

console.log('=== A: ETH/15m MFI Deep Iteration ===');
(function(){var c=getCandles('ETH','15m');var op=c.map(function(x){return x.open;}),hi=c.map(function(x){return x.high;});var lo=c.map(function(x){return x.low;}),cl=c.map(function(x){return x.close;});var vo=c.map(function(x){return x.volume;}),ti=c.map(function(x){return x.open_time;});
var cfgs=[[10,80,20,2.2,2,[10,11,12,21]],[10,80,20,2.2,2,[10,11,12,13,21]],[10,80,20,2.2,2,[9,10,11,12,21,22]],[10,80,15,2.2,2,[10,11,12,21]],[10,80,15,2.0,2,[10,11,12,21]],[10,80,20,2.0,2,[10,11,12,21]],[10,80,20,2.2,1,[10,11,12,21]],[10,80,20,2.2,3,[10,11,12,21]],[10,75,20,2.2,2,[10,11,12,21]],[10,80,20,2.2,2,null],[10,80,20,2.5,2,[10,11,12,21]],[8,80,20,2.2,2,[10,11,12,21]]];
cfgs.forEach(function(cfg){var mP=cfg[0],mT=cfg[1],bP=cfg[2],bM=cfg[3],s=cfg[4],hrs=cfg[5];var bb=calcBB(cl,bP,bM);var mfi=calcMFI(hi,lo,cl,vo,mP);var hS=hrs?new Set(hrs):null;var wu=Math.max(mP,bP)+2;var sigs=[];for(var i=wu;i<c.length-1;i++){var hr=new Date(ti[i]).getUTCHours();if(hS&&!hS.has(hr))continue;if(!bb[i]||mfi[i]===null)continue;var t=sk(op,cl,i);if(t.streak<s)continue;if(t.dir===1&&mfi[i]>=mT&&cl[i]>=bb[i].upper)sigs.push({win:c[i+1].close<c[i+1].open});else if(t.dir===-1&&mfi[i]<=(100-mT)&&cl[i]<=bb[i].lower)sigs.push({win:c[i+1].close>c[i+1].open});}var hL=hrs?'['+hrs.join(',')+']':'allH';rep('MFI('+mP+')>'+mT+' BB('+bP+','+bM+') s>='+s+' H='+hL,sigs);});})();

console.log('');
console.log('=== B: Day-of-Week Combos ===');
(function(){var dc=[[[3],'Wed'],[[3,6],'Wed+Sat'],[[2,3],'Tue+Wed'],[[3,4],'Wed+Thu'],[[2,3,6],'Tue+Wed+Sat'],[[0,3,6],'Sun+Wed+Sat'],[[3,5,6],'Wed+Fri+Sat']];['5m','15m'].forEach(function(tf){var c=getCandles('ETH',tf);var op=c.map(function(x){return x.open;}),cl=c.map(function(x){return x.close;}),ti=c.map(function(x){return x.open_time;});var bP=tf==='5m'?20:15;var bb=calcBB(cl,bP,2.2);var wu=bP+3;dc.forEach(function(d){var dS=new Set(d[0]),lbl=d[1];var sigs=[];for(var i=wu;i<c.length-1;i++){var dt=new Date(ti[i]);if(!dS.has(dt.getUTCDay()))continue;if(!GH.has(dt.getUTCHours()))continue;if(!bb[i])continue;var t=sk(op,cl,i);if(t.streak<2)continue;if(t.dir===1&&cl[i]>=bb[i].upper)sigs.push({win:c[i+1].close<c[i+1].open});else if(t.dir===-1&&cl[i]<=bb[i].lower)sigs.push({win:c[i+1].close>c[i+1].open});}if(sigs.length>=20){var r=wf(sigs);if(r.avgWR>=63){var fs=r.folds.map(function(f){return(f.wr*100).toFixed(1)+'%['+f.n+']';}).join('/');var p=r.avgWR>=65&&r.sigma<=8&&r.total>=50;console.log(lbl+' GoodH BB('+bP+',2.2) s>=2 ['+tf+']: WR='+r.avgWR.toFixed(1)+'% sigma='+r.sigma.toFixed(1)+'% T='+r.total+' ['+fs+'] '+(p?'*** PASS ***':''));}}});});})();

console.log('');
console.log('=== C: Range Breakout Iteration ===');
(function(){var c=getCandles('ETH','5m');var hi=c.map(function(x){return x.high;}),lo=c.map(function(x){return x.low;}),cl=c.map(function(x){return x.close;}),ti=c.map(function(x){return x.open_time;});[36,48,60,72,96].forEach(function(rl){[2.0,2.2,2.5].forEach(function(bm){[true,false].forEach(function(gH){var bb=calcBB(cl,20,bm);var sigs=[];for(var i=rl+20;i<c.length-1;i++){var hr=new Date(ti[i]).getUTCHours();if(gH&&!GH.has(hr))continue;if(!bb[i])continue;var rh=-Infinity,rl2=Infinity;for(var j=i-rl;j<i;j++){if(hi[j]>rh)rh=hi[j];if(lo[j]<rl2)rl2=lo[j];}if(cl[i]>rh&&cl[i]>=bb[i].upper)sigs.push({win:c[i+1].close<c[i+1].open});if(cl[i]<rl2&&cl[i]<=bb[i].lower)sigs.push({win:c[i+1].close>c[i+1].open});}if(sigs.length>=30){var r=wf(sigs);if(r.avgWR>=62){var fs=r.folds.map(function(f){return(f.wr*100).toFixed(1)+'%['+f.n+']';}).join('/');var p=r.avgWR>=65&&r.sigma<=8&&r.total>=50;console.log('Range('+rl+')+BB(20,'+bm+') GoodH='+gH+': WR='+r.avgWR.toFixed(1)+'% sigma='+r.sigma.toFixed(1)+'% T='+r.total+' ['+fs+'] '+(p?'*** PASS ***':''));}}});});});})();

console.log('');
console.log('=== D: Streak=4/5 Variants ===');
(function(){var c=getCandles('ETH','5m');var op=c.map(function(x){return x.open;}),cl=c.map(function(x){return x.close;}),ti=c.map(function(x){return x.open_time;});[4,5].forEach(function(es){[2.0,2.2,2.5].forEach(function(bm){[true,false].forEach(function(gH){var bb=calcBB(cl,20,bm);var sigs=[];for(var i=25;i<c.length-1;i++){var hr=new Date(ti[i]).getUTCHours();if(gH&&!GH.has(hr))continue;if(!bb[i])continue;var t=sk(op,cl,i);if(t.streak!==es)continue;if(t.dir===1&&cl[i]>=bb[i].upper)sigs.push({win:c[i+1].close<c[i+1].open});else if(t.dir===-1&&cl[i]<=bb[i].lower)sigs.push({win:c[i+1].close>c[i+1].open});}if(sigs.length>=20){var r=wf(sigs);if(r.avgWR>=63){var fs=r.folds.map(function(f){return(f.wr*100).toFixed(1)+'%['+f.n+']';}).join('/');var p=r.avgWR>=65&&r.sigma<=8&&r.total>=50;console.log('s='+es+' BB(20,'+bm+') GoodH='+gH+': WR='+r.avgWR.toFixed(1)+'% sigma='+r.sigma.toFixed(1)+'% T='+r.total+' ['+fs+'] '+(p?'*** PASS ***':''));}}});});});})();